server.port=${PORT:8080}

spring.application.name=nexusdistapi
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
